<?php
include_once('./_common.php');
$g5['title'] = '조직도';
include_once(G5_PATH.'/head.php');
?>

<div class="cont organization">

    <div class="box">
        <table class="basic-type02" cellspacing="0" cellpadding="0">
            <thead>
                <tr>
                    <th colspan="4">회장단</th>
                </tr>
                <tr>
                    <th>직위</th>
                    <th>성명</th>
                    <th colspan="2" class="text-center">과,기수</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>총동문회장</td>
                    <td>이찬용</td>
                    <td>전기</td>
                    <td>38</td>
                </tr>
                <tr>
                    <td>수석부회장</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>선임감사</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>감사</td>
                    <td>김평희</td>
                    <td>전기</td>
                    <td>38</td>
                </tr>
				<tr>
                    <td>사무처장</td>
                    <td>성락기</td>
                    <td>전기</td>
                    <td>40</td>
                </tr>
				<tr>
                    <td>사무부장</td>
                    <td>이용민</td>
                    <td>기계</td>
                    <td>54</td>
                </tr>
				<tr>
                    <td>총무이사</td>
                    <td>지주현</td>
                    <td>기계</td>
                    <td>41</td>
                </tr>
				<tr>
                    <td>총무부장</td>
                    <td>이문규</td>
                    <td>토목</td>
                    <td>51</td>
                </tr>
				<tr>
                    <td>재무이사</td>
                    <td>손화춘</td>
                    <td>기계</td>
                    <td>43</td>
                </tr>
				<tr>
                    <td>재무부장</td>
                    <td>허  욱</td>
                    <td>토목</td>
                    <td>52</td>
                </tr>
				<tr>
                    <td>홍보이사</td>
                    <td>유형용</td>
                    <td>기계</td>
                    <td>40</td>
                </tr>
				<tr>
                    <td>홍보부장</td>
                    <td>박주환</td>
                    <td>기계</td>
                    <td>59</td>
                </tr>
				<tr>
                    <td>기획이사</td>
                    <td>이  근</td>
                    <td>전기</td>
                    <td>41</td>
                </tr>
				<tr>
                    <td>기획부장</td>
                    <td>이종억</td>
                    <td>전기</td>
                    <td>54</td>
                </tr>
				<tr>
                    <td>조직이사</td>
                    <td>이상일</td>
                    <td>자동차</td>
                    <td>46</td>
                </tr>
				<tr>
                    <td>조직부장</td>
                    <td>최영범</td>
                    <td>기계</td>
                    <td>52</td>
                </tr>
				<tr>
                    <td>체육이사</td>
                    <td>위인환</td>
                    <td>건축</td>
                    <td>45</td>
                </tr>
				<tr>
                    <td>체육부장</td>
                    <td>김복룡</td>
                    <td>기계</td>
                    <td>51</td>
                </tr>
				<tr>
                    <td>복지사업이사</td>
                    <td>박귀선</td>
                    <td>토목</td>
                    <td>45</td>
                </tr>
				<tr>
                    <td>복지사업부장</td>
                    <td>장승학</td>
                    <td>기계</td>
                    <td>59</td>
                </tr>
				<tr>
                    <td>대외협력이사</td>
                    <td>박돈남</td>
                    <td>기계</td>
                    <td>43</td>
                </tr>
				<tr>
                    <td>대외협력부장</td>
                    <td>박종범</td>
                    <td>토목</td>
                    <td>51</td>
                </tr>
				<tr>
                    <td>장학회이사장</td>
                    <td>이건직</td>
                    <td>기계</td>
                    <td>37</td>
                </tr>
            </tbody>
        </table>
    </div>

    <!-- 과별 -->
    <div class="box">
        <table class="basic-type02" cellspacing="0" cellpadding="0">
            <thead>
                <tr>
                    <th colspan="4">과별</th>
                </tr>
                <tr>
                    <th>직위</th>
                    <th>성명</th>
                    <th colspan="2" class="text-center">과,기수</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>기계과회장</td>
                    <td>배상우</td>
                    <td>기계</td>
                    <td>38</td>
                </tr>
				<tr>
                    <td>기계과사무국장</td>
                    <td>손화춘</td>
                    <td>기계</td>
                    <td>43</td>
                </tr>
				<tr>
                    <td>전기과회장</td>
                    <td>오명식</td>
                    <td>전기</td>
                    <td>38</td>
                </tr>
				<tr>
                    <td>전기과사무국장</td>
                    <td>김동진</td>
                    <td>전기</td>
                    <td>48</td>
                </tr>
				<tr>
                    <td>건축과회장</td>
                    <td>곽수영</td>
                    <td>건축</td>
                    <td>35</td>
                </tr>
				<tr>
                    <td>건축과사무국장</td>
                    <td>위인환</td>
                    <td>건축</td>
                    <td>45</td>
                </tr>
				<tr>
                    <td>토목과회장</td>
                    <td>김희동</td>
                    <td>토목</td>
                    <td>35</td>
                </tr>
				<tr>
                    <td>토목과사무국장</td>
                    <td>김광운</td>
                    <td>토목</td>
                    <td>46</td>
                </tr>
				<tr>
                    <td>자동차과회장</td>
                    <td>최병근</td>
                    <td>자동차</td>
                    <td>34</td>
                </tr>
				<tr>
                    <td>자동차과사무국장</td>
                    <td>이상일</td>
                    <td>자동차</td>
                    <td>46</td>
                </tr>
				<tr>
                    <td>배관과회장</td>
                    <td>금인선</td>
                    <td>배관</td>
                    <td>42</td>
                </tr>
				<tr>
                    <td>화공과회장</td>
                    <td>이장원</td>
                    <td>화공</td>
                    <td>32</td>
                </tr>
            </tbody>
        </table>
    </div>

    <!-- 각 지회 -->
    <div class="box">
        <table class="basic-type02" cellspacing="0" cellpadding="0">
            <thead>
                <tr>
                    <th colspan="4">각 지회</th>
                </tr>
                <tr>
                    <th>직위</th>
                    <th>성명</th>
                    <th colspan="2" class="text-center">과,기수</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>엘리펀츠야구단</td>
                    <td>이병구</td>
                    <td>전기</td>
                    <td>45</td>
                </tr>
				<tr>
                    <td>사무국장</td>
                    <td>여국현</td>
                    <td>자동차</td>
                    <td>56</td>
                </tr>
				<tr>
                    <td>동문회골프회장</td>
                    <td>정상헌</td>
                    <td>건축</td>
                    <td>33</td>
                </tr>
				<tr>
                    <td>관악부회장</td>
                    <td>장영범</td>
                    <td>기계</td>
                    <td>44</td>
                </tr>
				<tr>
                    <td>관악부사무국장</td>
                    <td>김동수</td>
                    <td>전기</td>
                    <td>47</td>
                </tr>
				<tr>
                    <td>코끼리봉사단단장</td>
                    <td>지주현</td>
                    <td>기계</td>
                    <td>41</td>
                </tr>
				<tr>
                    <td>사무국장</td>
                    <td>이용민</td>
                    <td>기계</td>
                    <td>54</td>
                </tr>
				<tr>
                    <td>41회기수회장</td>
                    <td>선종길</td>
                    <td>기계</td>
                    <td>41</td>
                </tr>
				<tr>
                    <td>시흥지회장</td>
                    <td>신영익</td>
                    <td>건축</td>
                    <td>34</td>
                </tr>
				<tr>
                    <td>총무</td>
                    <td>이현수</td>
                    <td>기계</td>
                    <td>40</td>
                </tr>
				<tr>
                    <td>강화지회장</td>
                    <td>방명일</td>
                    <td>기계</td>
                    <td>31</td>
                </tr>
				<tr>
                    <td>총무</td>
                    <td>한경희</td>
                    <td>배관</td>
                    <td>38</td>
                </tr>
				<tr>
                    <td>상아지회장</td>
                    <td>권달우</td>
                    <td>기계</td>
                    <td>36</td>
                </tr>
				<tr>
                    <td>수봉산악지회장</td>
                    <td>임종안</td>
                    <td>토목</td>
                    <td>46</td>
                </tr>
				<tr>
                    <td>총무</td>
                    <td>한석준</td>
                    <td>토목</td>
                    <td>47</td>
                </tr>
				<tr>
                    <td>코끼리산악지회장</td>
                    <td>강영구</td>
                    <td>화공</td>
                    <td>34</td>
                </tr>
				<tr>
                    <td>코끼리산악지회장</td>
                    <td>강영구</td>
                    <td>화공</td>
                    <td>34</td>
                </tr>
				<tr>
                    <td>총무</td>
                    <td>김장원</td>
                    <td>화공</td>
                    <td>34</td>
                </tr>
				<tr>
                    <td>수봉회지회장</td>
                    <td>신동영</td>
                    <td>전기</td>
                    <td>38</td>
                </tr>
				<tr>
                    <td>총무</td>
                    <td>함은규</td>
                    <td>전기</td>
                    <td>41</td>
                </tr>
				<tr>
                    <td>동구지회장</td>
                    <td>채지희</td>
                    <td>기계</td>
                    <td>32</td>
                </tr>
				<tr>
                    <td>총무</td>
                    <td>정인교</td>
                    <td>기계</td>
                    <td>40</td>
                </tr>
				<tr>
                    <td>서구지회장</td>
                    <td>송창규</td>
                    <td>화공</td>
                    <td>31</td>
                </tr>
				<tr>
                    <td>총무</td>
                    <td>정용섭</td>
                    <td>건축</td>
                    <td>35</td>
                </tr>
				<tr>
                    <td>김포지회장</td>
                    <td>엄광용</td>
                    <td>금속</td>
                    <td>41</td>
                </tr>
				<tr>
                    <td>총무</td>
                    <td>정웅모</td>
                    <td>기계</td>
                    <td>40</td>
                </tr>
				<tr>
                    <td>인천시백상회회장</td>
                    <td>반상용</td>
                    <td>기계</td>
                    <td>38</td>
                </tr>
				<tr>
                    <td>총무</td>
                    <td>신남희</td>
                    <td>기계</td>
                    <td>38</td>
                </tr>
				<tr>
                    <td>인공회장</td>
                    <td>금종설</td>
                    <td>금속</td>
                    <td>39</td>
                </tr>
				<tr>
                    <td>효성지회</td>
                    <td>이강수</td>
                    <td>전기</td>
                    <td>32</td>
                </tr>
				<tr>
                    <td>총무</td>
                    <td>김준택</td>
                    <td>자동차</td>
                    <td>35</td>
                </tr>
            </tbody>
        </table>
    </div>

    <?php
include_once(G5_PATH.'/tail.php');
?>

